services:
  db:
    image: postgres:16
    container_name: splitrackr-db
    environment:
      POSTGRES_DB: splitrackr
      POSTGRES_USER: splitrackr
      POSTGRES_PASSWORD: splitrackr
    ports:
      - "55432:5432"              # host:container
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  db_data:

